version: '3.8'
services:
  db:
    image: postgres:18
    container_name: labellingproject-db
    restart: always
    ports:
      - "${MYSQL_DATABASE}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${MYSQL_DATABASE}
    # mount volume trực tiếp vào /var/lib/postgresql, PostgreSQL 18+ sẽ tự tạo subfolder
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
